version: "3"
services:
  web:
    image: abiosoft/caddy
    container_name: web
    hostname: mydomain.io
    volumes:
      - "./Caddyfile:/etc/Caddyfile"
      - "./web:/web"
      - "./cert.pem:/cert.pem"
      - "./key.pem:/key.pem"
    working_dir: "/web"
    ports:
      - "80:80"
      - "443:443"

  server:
    image: golang:alpine
    command: sh -c "apk add --update make git && make setup && make run"
    container_name: server
    hostname: server
    working_dir: "/src"
    volumes:
      - "$PWD/server:/src"
    ports:
      - "5000:5000"
    expose:
      - "5000"

  envoy:
    image: envoyproxy/envoy
    container_name: envoy
    hostname: envoy
    command: envoy -c /etc/envoy.yaml
    volumes:
      - "./envoy.yaml:/etc/envoy.yaml"
      - "./cert.pem:/etc/cert.pem"
      - "./key.pem:/etc/key.pem"
    expose:
      - "4443"
    ports:
      - "9901:9901"
      - "4443:4443"
    depends_on:
      - server

  nginx:
    image: nginx
    container_name: nginx
    hostname: mydomain.io
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx.default:/etc/nginx/conf.d/default.conf"
      - "./web:/usr/share/nginx/html"
      - "./cert.pem:/etc/cert.pem"
      - "./key.pem:/etc/key.pem"
    # ports:
      # - "80:80"
      # - "443:443"
    depends_on:
      - server
